######################################################################
##
## Filename: fir.udo
## Created on: Tue Apr 30 07:02:18 PM CDT 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
